spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/lingua}
    username: ${DATABASE_USER:lingua}
    password: ${DATABASE_PASSWORD:lingua}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    format-sql: true
server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET:ff448f84-686c-47fc-a563-432711006f5a}
