CREATE TABLE story
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    content     VARCHAR(255),
    level       VARCHAR(255),
    language_id BIGINT,
    cover       VARCHAR(255),
    CONSTRAINT pk_story PRIMARY KEY (id)
);

ALTER TABLE story
    ADD CONSTRAINT FK_STORY_ON_LANGUAGE FOREIGN KEY (language_id) REFERENCES language (id);
CREATE TABLE story_quiz
(
    story_id BIGINT NOT NULL,
    quiz_id  BIGINT NOT NULL
);

ALTER TABLE story_quiz
    ADD CONSTRAINT fk_stoqui_on_question FOREIGN KEY (quiz_id) REFERENCES question (id);

ALTER TABLE story_quiz
    ADD CONSTRAINT fk_stoqui_on_story FOREIGN KEY (story_id) REFERENCES story (id);
CREATE TABLE story_vocabulary
(
    story_id      BIGINT NOT NULL,
    vocabulary_id BIGINT NOT NULL
);

ALTER TABLE story_vocabulary
    ADD CONSTRAINT fk_stovoc_on_story FOREIGN KEY (story_id) REFERENCES story (id);

ALTER TABLE story_vocabulary
    ADD CONSTRAINT fk_stovoc_on_word FOREIGN KEY (vocabulary_id) REFERENCES word (id);